### ISSUE TITLE
Support CentOS 8

### ISSUE THREAD

**Issue by ThirstySpace** [robertdebock/ansible-role-omsagent#2]
## Proposed feature

Please add support for CentOS 8 by removing python-ctypes from requirements.

## Rationale

This feature would be great, because CentOS 8 is supported by latest release of omsagent.

## Additional context

Let me know if any additional context is needed.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
I'll work on this, thanks for taking the time to create an issue.

**Comment by robertdebock** [comment]
We'll have to wait a while, I pushed many changes a moment ago, CI will test these changes later, hopefully today.

When that's done, I'll need to release a new version before you can pick it up from Galaxy.

**Comment by ThirstySpace** [comment]
Thank you for your fast response.

**Comment by robertdebock** [comment]
Version 1.2.2 has the changes and should be ready to use in a minute or so.
